<script setup lang="ts">
type Field = { name: string; label: string; type?: string; required?: boolean; options?: string[]; hint?: string }
type Profile = { title: string; intro: string; fields: Field[] }
type EndpointSuccess = { success: true; data?: { redirect_url?: string; thank_you_content?: string } }
type EndpointFailure = { success: false; message?: string }

const profiles: Record<string, Profile> = {
  'contact-form': { title: 'Contact form', intro: 'A clear starting point for general enquiries.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'subject', label: 'Subject', required: true }, { name: 'message', label: 'Message', type: 'textarea', required: true }] },
  'newsletter-signup-form': { title: 'Newsletter signup', intro: 'Collect permission-based email interest; it does not send campaigns.', fields: [{ name: 'email', label: 'Email', type: 'email', required: true }, { name: 'first_name', label: 'First name' }, { name: 'consent', label: 'I agree to receive updates', type: 'checkbox', required: true }] },
  'waitlist-form': { title: 'Product waitlist', intro: 'Learn who wants early access and why.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'use_case', label: 'Company or use case', required: true }, { name: 'note', label: 'Anything else?', type: 'textarea' }] },
  'lead-generation-form': { title: 'Lead generation form', intro: 'Collect enough context for a useful sales follow-up.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'business_email', label: 'Business email', type: 'email', required: true }, { name: 'company', label: 'Company', required: true }, { name: 'website', label: 'Website', type: 'url' }, { name: 'company_size', label: 'Company size', type: 'select', options: ['1–10', '11–50', '51–200', '201+'] }, { name: 'interest', label: 'What are you interested in?', required: true }, { name: 'message', label: 'Message', type: 'textarea' }] },
  'demo-request-form': { title: 'Demo request', intro: 'Capture product context before arranging a demonstration.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'work_email', label: 'Work email', type: 'email', required: true }, { name: 'company', label: 'Company', required: true }, { name: 'role', label: 'Role', required: true }, { name: 'company_size', label: 'Company size', type: 'select', options: ['1–10', '11–50', '51–200', '201+'] }, { name: 'preferred_time', label: 'Preferred time' }, { name: 'requirements', label: 'Requirements', type: 'textarea' }] },
  'quote-request-form': { title: 'Quote request', intro: 'Gather project requirements before providing a quote.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'company', label: 'Company' }, { name: 'service', label: 'Service', required: true }, { name: 'project_type', label: 'Project type', required: true }, { name: 'budget', label: 'Budget range', type: 'select', options: ['Under $5,000', '$5,000–$15,000', '$15,000+'] }, { name: 'desired_start_date', label: 'Desired start date', type: 'date' }, { name: 'details', label: 'Project details', type: 'textarea', required: true }] },
  'booking-request-form': { title: 'Booking request', intro: 'This requests a booking; it does not confirm live availability.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'phone', label: 'Phone', type: 'tel', required: true }, { name: 'service', label: 'Service', required: true }, { name: 'requested_date', label: 'Requested date', type: 'date', required: true }, { name: 'requested_time', label: 'Requested time', type: 'time', required: true }, { name: 'notes', label: 'Notes', type: 'textarea' }] },
  'event-registration-form': { title: 'Event registration', intro: 'Register an attendee and collect practical event details.', fields: [{ name: 'attendee_name', label: 'Attendee name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'event_session', label: 'Event or session', required: true }, { name: 'organization', label: 'Organization' }, { name: 'accessibility_notes', label: 'Dietary or accessibility notes', type: 'textarea' }] },
  'job-application-form': { title: 'Job application', intro: 'A role-specific application that requests links rather than file uploads.', fields: [{ name: 'full_name', label: 'Full name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'phone', label: 'Phone', type: 'tel' }, { name: 'position', label: 'Position', required: true }, { name: 'portfolio_url', label: 'Portfolio or resume URL', type: 'url', required: true }, { name: 'linkedin_url', label: 'LinkedIn URL', type: 'url' }, { name: 'cover_note', label: 'Cover note', type: 'textarea', required: true }] },
  'feedback-form': { title: 'Feedback form', intro: 'Capture a rating and actionable feedback.', fields: [{ name: 'name', label: 'Name' }, { name: 'email', label: 'Email', type: 'email' }, { name: 'rating', label: 'Rating', type: 'select', required: true, options: ['1 — Poor', '2', '3', '4', '5 — Excellent'] }, { name: 'feedback', label: 'What could we improve?', type: 'textarea', required: true }] },
  'survey-form': { title: 'Survey form', intro: 'Collect structured feedback without asking for sensitive information.', fields: [{ name: 'email', label: 'Email (optional)', type: 'email' }, { name: 'satisfaction', label: 'Overall satisfaction', type: 'select', required: true, options: ['Very dissatisfied', 'Dissatisfied', 'Neutral', 'Satisfied', 'Very satisfied'] }, { name: 'recommendation', label: 'Would you recommend us?', type: 'select', required: true, options: ['Yes', 'No', 'Not sure'] }, { name: 'comments', label: 'Comments', type: 'textarea' }] },
  'support-request-form': { title: 'Support request', intro: 'Collect reproduction details so the support team can help.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'product', label: 'Product or service', required: true }, { name: 'priority', label: 'Impact', type: 'select', options: ['Low', 'Normal', 'High'] }, { name: 'details', label: 'What happened?', type: 'textarea', required: true }, { name: 'steps_to_reproduce', label: 'Steps to reproduce', type: 'textarea' }] },
  'multi-step-lead-form': { title: 'Multi-step lead form', intro: 'This profile uses the same safe submit flow; see its README for step-by-step validation.', fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'company', label: 'Company', required: true }, { name: 'project', label: 'Project', required: true }, { name: 'budget', label: 'Budget', required: true }, { name: 'timeline', label: 'Timeline', required: true }] }
}
const config = useRuntimeConfig()
function makeProfile(slug: string): Profile {
  const label = slug.replace(/-/g, ' ').replace(/\b\w/g, letter => letter.toUpperCase())
  const base: Field[] = [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }]
  if (/(registration|rsvp|workshop|course|event)/.test(slug)) return { title: label, intro: 'A registration template with attendance-specific information.', fields: [...base, { name: 'selection', label: 'Event, course, or session', required: true }, { name: 'organization', label: 'Organization' }, { name: 'notes', label: 'Accessibility or other notes', type: 'textarea' }] }
  if (/(application|membership|volunteer|internship)/.test(slug)) return { title: label, intro: 'An application template that uses links rather than direct file uploads.', fields: [...base, { name: 'role_or_type', label: 'Role or application type', required: true }, { name: 'portfolio_url', label: 'Portfolio or resume URL', type: 'url' }, { name: 'statement', label: 'Why are you applying?', type: 'textarea', required: true }] }
  if (/(booking|appointment|reservation|viewing|consultation|callback)/.test(slug)) return { title: label, intro: 'A request form; it does not claim real-time availability.', fields: [...base, { name: 'phone', label: 'Phone', type: 'tel', required: true }, { name: 'request_type', label: 'Request type', required: true }, { name: 'preferred_date', label: 'Preferred date', type: 'date' }, { name: 'preferred_time', label: 'Preferred time', type: 'time' }, { name: 'notes', label: 'Notes', type: 'textarea' }] }
  if (/(survey|feedback|satisfaction|complaint|bug|feature|support)/.test(slug)) return { title: label, intro: 'A feedback template that collects context for a useful follow-up.', fields: [...base, { name: 'topic', label: 'Topic', required: true }, { name: 'rating_or_impact', label: 'Rating or impact', type: 'select', options: ['Low', 'Medium', 'High'] }, { name: 'details', label: 'Details', type: 'textarea', required: true }] }
  return { title: label, intro: 'A purpose-built Nuxt form template.', fields: [...base, { name: 'company', label: 'Company or organization' }, { name: 'request', label: 'What do you need?', required: true }, { name: 'details', label: 'Details', type: 'textarea' }] }
}
const profile = computed(() => profiles[config.public.formProfile] || makeProfile(config.public.formProfile))
const form = reactive<Record<string, string | boolean>>({})
const status = ref<'idle' | 'sending' | 'success' | 'error'>('idle')
const message = ref('')
function resetForm() { profile.value.fields.forEach(field => { form[field.name] = field.type === 'checkbox' ? false : '' }) }
resetForm()
async function submitForm() {
  if (!config.public.smartformifyEndpoint) { status.value = 'error'; message.value = 'Add NUXT_PUBLIC_SMARTFORMIFY_ENDPOINT to .env before submitting.'; return }
  status.value = 'sending'; message.value = ''
  try {
    const result = await $fetch<EndpointSuccess | EndpointFailure>(config.public.smartformifyEndpoint, { method: 'POST', body: { data: { ...form } } })
    if (!result.success) throw new Error(result.message || 'The endpoint did not accept this submission.')
    if (result.data?.redirect_url) { await navigateTo(result.data.redirect_url, { external: true }); return }
    status.value = 'success'; message.value = result.data?.thank_you_content || 'Thanks — your submission was received.'; resetForm()
  } catch (error) { status.value = 'error'; message.value = error instanceof Error ? error.message : 'Network error. Your details are still in the form; please try again.' }
}
</script>

<template>
  <main><section class="card"><p class="eyebrow">Nuxt 4 form template</p><h1>{{ profile.title }}</h1><p>{{ profile.intro }}</p>
    <form @submit.prevent="submitForm"><div v-for="field in profile.fields" :key="field.name" class="field"><label :for="field.name">{{ field.label }}</label>
      <textarea v-if="field.type === 'textarea'" :id="field.name" v-model="form[field.name] as string" :name="field.name" :required="field.required" maxlength="5000" />
      <select v-else-if="field.type === 'select'" :id="field.name" v-model="form[field.name] as string" :name="field.name" :required="field.required"><option value="" disabled>Select one</option><option v-for="option in field.options" :key="option">{{ option }}</option></select>
      <label v-else-if="field.type === 'checkbox'" class="check"><input :id="field.name" v-model="form[field.name] as boolean" :name="field.name" type="checkbox" :required="field.required"> {{ field.label }}</label>
      <input v-else :id="field.name" v-model="form[field.name] as string" :name="field.name" :type="field.type || 'text'" :required="field.required" :maxlength="field.type === 'email' ? undefined : 5000">
    </div><button :disabled="status === 'sending'">{{ status === 'sending' ? 'Sending…' : 'Send request' }}</button><p v-if="status !== 'idle'" :class="status" aria-live="polite">{{ message }}</p></form>
  </section></main>
</template>

<style>
*{box-sizing:border-box}body{margin:0;background:#f7f8fa;color:#172033;font:16px/1.5 system-ui,sans-serif}main{padding:3rem 1rem}.card{max-width:680px;margin:auto;background:white;padding:2rem;border:1px solid #e4e7ec;border-radius:14px;box-shadow:0 8px 24px #1720330d}.eyebrow{color:#00a86b;font-weight:700;text-transform:uppercase;font-size:.78rem;letter-spacing:.08em}h1{margin:.25rem 0}.field{display:grid;gap:.35rem;margin:1rem 0}label{font-weight:650}input,textarea,select{font:inherit;padding:.7rem;border:1px solid #aeb7c5;border-radius:7px;width:100%}textarea{min-height:7rem}.check{font-weight:400;display:flex;gap:.5rem;align-items:center}.check input{width:auto}button{font:inherit;font-weight:700;border:0;border-radius:7px;padding:.75rem 1rem;background:#00a86b;color:#fff;cursor:pointer}button:disabled{opacity:.65;cursor:wait}input:focus,textarea:focus,select:focus,button:focus{outline:3px solid #86efac;outline-offset:2px}.success{color:#057a55}.error{color:#b42318}@media(max-width:500px){main{padding:1rem}.card{padding:1.25rem}}
</style>
